"""Configuration constants for neural structural optimization models."""

# Default model parameters
DEFAULT_LATENT_SIZE = 128
DEFAULT_DENSE_CHANNELS = 32
DEFAULT_CONV_UPSAMPLE = (1, 2, 2, 2, 1)
DEFAULT_CONV_FILTERS = (128, 64, 32, 16, 1)
DEFAULT_OFFSET_SCALE = 10.0
DEFAULT_KERNEL_SIZE = 5
DEFAULT_NEG_SLOPE = 0.2
DEFAULT_CONV_INITIALIZER = "kaiming_fan_in"

# Physics computation settings
DEFAULT_MAX_ANALYSIS_DIM = 500
DEFAULT_TEMPERATURE = 1.4
DEFAULT_EPSILON = 1e-5
DEFAULT_VOID_DENSITY = 0.0

# Upsampling settings
DEFAULT_PRESERVE_MEAN = True
DEFAULT_FREEZE_TRANSFERRED = True
DEFAULT_DISTILL_WEIGHT = 0.1
DEFAULT_WARM_TAU = 0.25

# Optimization settings
DEFAULT_MAX_NEWTON_ITERATIONS = 8
DEFAULT_MEAN_TOLERANCE = 1e-4
DEFAULT_STEP_TOLERANCE = 1e-6
DEFAULT_MEAN_CONVERGENCE = 1e-6
